# Generated by Django 5.1.2 on 2024-11-08 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservationID', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.admin')),
            ],
        ),
    ]
