# Generated by Django 5.1.2 on 2024-11-08 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('feedbackID', models.AutoField(primary_key=True, serialize=False)),
                ('customerFeedback', models.CharField(max_length=500)),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.admin')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_feedbacks', to='customers.customer')),
            ],
        ),
    ]
