# Generated by Django 5.1.2 on 2024-11-08 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerUnit',
            fields=[
                ('computerID', models.AutoField(primary_key=True, serialize=False)),
                ('availability', models.BooleanField(default=True)),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.admin')),
            ],
        ),
    ]
