# Generated by Django 5.1.2 on 2024-11-08 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        ('computerunit', '0001_initial'),
        ('customers', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('sessionID', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.admin')),
                ('computerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computerunit.computerunit')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('reservationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservations')),
            ],
        ),
    ]
